fixes shad0w #3035
BlackArch/blackarch pull request #3043
Opened 2021-03-04 02:08 UTC by dualfade

please review --

2021-03-04 03:04 UTC, Edu4rdSHL commented
Hey @dualfade, thank you a lot, the style and PKGBUILD are perfect, anyway I'm having a problem when testing in a clean chroot env:

```
─▶ ba-dev -p shad0w-368.f4f7162-1-any.pkg.tar.zst -e "shad0w listen"
loading packages...
warning: shad0w-368.f4f7162-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) shad0w-368.f4f7162-1

Total Installed Size:  31.11 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) reinstalling shad0w                          [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Package shad0w-368.f4f7162-1-any.pkg.tar.zst installed correctly! Testing it now...
cp: cannot stat '/root/shad0w/beacon/lib/*': No such file or directory
Traceback (most recent call last):
  File "/usr/share/shad0w/shad0w.py", line 197, in <module>
    asyncio.run(shad0w.start())
  File "/usr/share/shad0w/shad0w.py", line 80, in start
    asyncio.run(tools.compile_and_store_static(self))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/share/shad0w/lib/tools.py", line 72, in compile_and_store_static
    buildtools.clone_source_files(rootdir="injectable", builddir=build_dir_name)
  File "/usr/share/shad0w/lib/buildtools.py", line 27, in clone_source_files
    os.chdir(basedir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/shad0w/beacon'
```
can you check this?

2021-03-04 12:33 UTC, dualfade commented
Let me double check.Listen requires sudo / root as it listens on port 443 by default. Ill ping back. Thanks !

2021-03-04 16:50 UTC, dualfade commented
@Edu4rdSHL This is hardcode -
https://github.com/bats3c/shad0w/blob/master/shad0w.py#L84

Are we good to make a patch ? -> /usr/share/shad0w/
Let me know. 
Thanks.

2021-03-04 16:56 UTC, Edu4rdSHL commented
As I suspected it was harcoded, yeah, make a patch and test it, if this works then submit it! Thank you

2021-03-04 16:57 UTC, dualfade commented
Awesome. Will do. Thanks !

2021-03-04 16:59 UTC, Edu4rdSHL commented
Looking the code, we can even remove that line. Try removing this and see if works as we already change the dir in the script that's put in /usr/bin

2021-03-04 20:24 UTC, dualfade commented
@Edu4rdSHL If you want to hold that is fine. Will containerize when needed as I have already done.

Thank you.,

2021-03-04 20:32 UTC, dualfade commented
@Edu4rdSHL 
Lets close this pull request ? Agree ?

2021-03-04 20:33 UTC, Edu4rdSHL commented
Let's convert it to draft :)

2021-03-04 20:35 UTC, dualfade commented
Ok awesome ! I will get  back to it in a bit. Rad. I'm game ;)

2021-03-05 14:45 UTC, Edu4rdSHL requested changes
Please see

2021-03-05 14:45 UTC, Edu4rdSHL commented on packages/shad0w/PKGBUILD
> +  wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb \
Please put this in `sources()`

2021-03-05 14:45 UTC, Edu4rdSHL commented on packages/shad0w/PKGBUILD
> +  ar x /tmp/packages-microsoft-prod.deb --output=/tmp/
It needs to be in `prepare()`

2021-03-05 14:45 UTC, Edu4rdSHL commented on packages/shad0w/PKGBUILD
> +    do sed -i 's/\/root\/shad0w/\/usr\/share\/shad0w/g' $i; done
```
  find ./ -iname *.pyc | xargs rm
  grep -Irl '/root/shad0w/' ./ | xargs sed -i 's/\/root\/shad0w/\/usr\/share\/shad0w/g'
```

2021-03-05 14:46 UTC, Edu4rdSHL commented on packages/shad0w/PKGBUILD
> +  ar x /tmp/packages-microsoft-prod.deb --output=/tmp/
Only line 38

2021-03-05 19:35 UTC, Edu4rdSHL approved these changes

2021-03-05 19:36 UTC, Edu4rdSHL commented
@dualfade thank you a lot for it, works perfectly!

2021-03-05 19:36 UTC, merged

2021-03-05 19:37 UTC, dualfade commented
> @dualfade thank you a lot for it, works perfectly!

awesome ! yeah very excited about this. Great tool. Thanks @Edu4rdSHL