[requested-tool] : PKGBUILD for crlfuzz
BlackArch/blackarch pull request #3144
Opened 2021-06-26 09:50 UTC by D4imyo

2021-06-26 09:59 UTC, Edu4rdSHL requested changes
Hello, thank you so much for it. Please fix it according to comments, also **always** follow our [PKGBUILD styles](https://github.com/BlackArch/blackarch-pkgbuilds). For Golang, [see it](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-go).

2021-06-26 09:59 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +pkgdesc='A fast tool to scan CRLF vulnerability written in Go'
Add final dot.
```suggestion
pkgdesc='A fast tool to scan CRLF vulnerability written in Go.'
```

2021-06-26 09:59 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +source=('git+https://github.com/dwisiswant0/crlfuzz.git')
Use variables whatever you can.
```suggestion
source=("git+https://github.com/dwisiswant0/$pkgname.git")
```

2021-06-26 09:59 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +arch=('any')
Golang packages produce binaries, add specific architectures.
```suggestion
arch=('x86_64' 'aarch64')
```

2021-06-26 09:59 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
Always leave an empty line between sections like `cd` and other commands after it.
```suggestion
  cd $pkgname
  
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```

2021-06-26 09:59 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +}
Follow our [build guidelines](https://github.com/BlackArch/blackarch-pkgbuilds/blob/9e4dffa5e8f5f74374a2a31daf8411a361a51376/PKGBUILD-go#L27-L43).

2021-06-26 09:59 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +}
Add EOF.

2021-06-26 10:02 UTC, Edu4rdSHL requested changes

2021-06-26 10:02 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +makedepends=('go')
Add `git` to makedepends. If you build in a clean chroot environment you have noticed it.

2021-06-26 10:36 UTC, Edu4rdSHL requested changes

2021-06-26 10:36 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +makedepends=('go' 'git')
Put makedepends before source.

2021-06-26 10:36 UTC, Edu4rdSHL commented on packages/crlfuzz/PKGBUILD
> +}
It's still missing.

2021-06-26 13:41 UTC, Edu4rdSHL approved these changes
Hey @D4imyo, thank you so much for it, really appreciated, splendid work. I will merge it once we finish an internal updating process!

2021-06-29 09:00 UTC, noptrix commented
hey guys, i didn't see this before and i commite dcrlfuzz already. closing issue

2021-06-29 09:00 UTC, closed without merging

2021-06-29 13:38 UTC, noraj commented
added in e33adf69c4cf569462a37061bf983987cb6ba8fa