Multiple tools
BlackArch/blackarch pull request #3196
Opened 2021-07-29 19:34 UTC by D4imyo

This PR fixes #2454, #2478,  #2610

regarding `densityscout`, i don't know exactly the version nor the groups of this tool

2021-07-29 22:20 UTC, noraj requested changes

2021-07-29 22:20 UTC, noraj commented on packages/beroot/PKGBUILD
> +license=('custom:unkown')
https://github.com/AlessandroZ/BeRoot/issues/36

We can't add copyrighted tools

2021-07-29 22:20 UTC, noraj commented on packages/densityscout/PKGBUILD
> +license=('custom:cert.at')
```diff
-license=('custom:cert.at')
+license=('ISC')
```

2021-07-29 22:20 UTC, noraj commented on packages/densityscout/PKGBUILD
> +    install -Dm 644 "$pkgname" "$pkgdir/usr/bin/$pkgname"
you can use only one `install -Dm 644 "$pkgname" "$pkgdir/usr/bin/$pkgname"` outside of the if/else block since it's the same in both cases

2021-07-29 22:45 UTC, D4imyo commented on packages/beroot/PKGBUILD
> +license=('custom:unkown')
so....should i remove its PKGBUILD ?

2021-07-30 08:40 UTC, noraj commented on packages/beroot/PKGBUILD
> +license=('custom:unkown')
The best would have been that you made 3 PR for the 3 tools and we would have let this one as WIP until a license is set upstream. You can maybe remove this one from this PR and add the PKGBUILD in a comment of the issue so someone would be able to PR when upstream would be ready.

2021-07-30 18:14 UTC, noptrix commented
@D4imyo thanks a lot. better do single issues for each tools. this is prefered. so we can squash and merge in. are you done with this issue, e.g. can we merge in?

2021-07-30 20:39 UTC, D4imyo commented
> @D4imyo thanks a lot. better do single issues for each tools. this is prefered. so we can squash and merge in. are you done with this issue, e.g. can we merge in?

yes, you can merge now.

2021-07-30 20:55 UTC, merged