proxmark3 : initial commit
BlackArch/blackarch pull request #3232
Opened 2021-09-08 15:02 UTC by D4imyo

closes #3191.
i had to add `PREFIX=/usr` because without it the installation process will raise an `permission denied` error while copying binaries.

2021-09-08 18:07 UTC, noraj approved these changes
LGTM but I didn't test

2021-09-13 19:09 UTC, noraj requested changes

2021-09-13 19:09 UTC, noraj commented on packages/proxmark3/PKGBUILD
> +groups=('blackarch' 'blackarch-misc')
Maybe `blackarch-hardware` and/or `blackarch-wireless`. See https://gist.github.com/noraj/5045be32490f1161161e16fc5820066c#ba to list categories. Try avoiding using misc by default but only when no category fits.

2021-09-13 19:11 UTC, noraj commented on packages/proxmark3/PKGBUILD
> +groups=('blackarch' 'blackarch-misc')
also see https://github.com/BlackArch/blackarch/blob/f27c5c54aaf4dfc1b1d4bbbd41110952dc5d7773/packages/proxmark/PKGBUILD#L7, there is the radio group.

2021-09-13 19:13 UTC, noraj commented
By the way what is the difference with https://github.com/Proxmark/proxmark3 that is also proxmark 3 and already packaged as `proxmark` on BA?

2021-09-13 19:19 UTC, noraj commented
Builds correctly: `ba-dev -e 'proxmark3 -h' -p proxmark3-v4.13441.r985.gb45602812-1-x86_64.pkg.tar.zst`

2021-09-13 19:40 UTC, D4imyo commented
> By the way what is the difference with https://github.com/Proxmark/proxmark3 that is also proxmark 3 and already packaged as `proxmark` on BA?

actually i didn't know that it's already packaged , but i think there's no difference between them.
what do you think ?

2021-09-13 20:04 UTC, D4imyo commented
oh i found the differences between them , here it is https://github.com/rfidresearchgroup/proxmark3#what-has-changed

2021-09-15 17:21 UTC, noraj commented
> oh i found the differences between them , here it is https://github.com/rfidresearchgroup/proxmark3#what-has-changed

So I guess it's valid to have both, maybe we should rename this one `proxmark3-rdv4`? What do you think @noptrix?

2021-09-16 07:13 UTC, noptrix commented
> > oh i found the differences between them , here it is https://github.com/rfidresearchgroup/proxmark3#what-has-changed
> 
> So I guess it's valid to have both, maybe we should rename this one `proxmark3-rdv4`? What do you think @noptrix?

yo, `proxmark3` is the way to go here. thank you guys.

2021-09-16 07:32 UTC, merged

2021-09-16 18:52 UTC, iceman1001 commented
the official repo  (proxmark/proxmark3)  vs rrg/iceman is quite changed.  While official repo has stagnated,  the latter is alive.

Thank you for adding it.

2021-09-16 18:53 UTC, iceman1001 commented
There is a package in the Pentoo which would be of assistance.   Since the Pm3 project has a client and a firmware part.