rustcat: initial commit
BlackArch/blackarch pull request #3233
Opened 2021-09-08 18:33 UTC by robiot

2021-09-08 19:51 UTC, D4imyo commented
hey, please look at `blackarch-pkgbuilds` repo so you can compare your work with it, like the order of variables,..etc

2021-09-08 20:03 UTC, D4imyo requested changes

2021-09-08 20:03 UTC, D4imyo commented on packages/rustcat/PKGBUILD
> +  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
https://github.com/BlackArch/blackarch-pkgbuilds/blob/057a20ced2a87770fb83d169c56956fab9055ccb/PKGBUILD-generic-git#L20-L24

2021-09-08 20:25 UTC, robiot commented
Thanks @D4imyo, I will fix this as fast as I can :)

2021-09-09 17:31 UTC, noraj requested changes

2021-09-09 17:31 UTC, noraj commented on packages/rustcat/PKGBUILD
> +  echo $(git describe --tags --abbrev=0 | cut -c 2-)
Use `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`, please follow https://github.com/BlackArch/blackarch-pkgbuilds

2021-09-09 18:53 UTC, robiot commented on packages/rustcat/PKGBUILD
> +  echo $(git describe --tags --abbrev=0 | cut -c 2-)
Fixed it!

2021-09-13 18:00 UTC, noraj requested changes

2021-09-13 18:00 UTC, noraj commented on packages/rustcat/PKGBUILD
> +    'rustup'
put them on one line until it is 80 chars line length

2021-09-13 18:00 UTC, noraj commented on packages/rustcat/PKGBUILD
> +    git checkout $(git describe --tags --abbrev=0) &> /dev/null
keep last commit, remove the checkout

2021-09-13 18:01 UTC, noraj commented
Also testing it in the current state fails:

```
$ ba-dev -b
...
error: no override and no default toolchain set
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/noraj/blackarch_chroot/blackarch/build
Failed to build the package.
```

2021-09-13 19:06 UTC, robiot commented
> Also testing it in the current state fails:
> 
> ```
> $ ba-dev -b
> ...
> error: no override and no default toolchain set
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ==> ERROR: Build failed, check /home/noraj/blackarch_chroot/blackarch/build
> Failed to build the package.
> ```

Fixed this, and the other errors. Also tried it with ba-dev and it succeded

2021-09-13 19:25 UTC, noraj commented
Builds correctly: `ba-dev -e 'rc -h' -p rustcat-v1.1.2.r2.g2cae2f9-1-x86_64.pkg.tar.zst`

2021-09-13 19:26 UTC, noraj approved these changes

2021-09-13 19:26 UTC, merged