postman: initial commit
BlackArch/blackarch pull request #3322
Opened 2022-01-24 21:52 UTC by ikstream

Signed-off-by: Stefan Venz <stefan.venz@protonmail.com>

2022-02-06 16:32 UTC, noraj requested changes
Postman is not a security tool and can already be installed via [AUR](https://aur.archlinux.org/packages/postman-bin).
I don't see the interest of adding it in BA.

2022-02-06 16:32 UTC, noraj commented on packages/postman/PKGBUILD
> +arch=('x86_64')
lacks a `groups`

2022-02-06 21:02 UTC, ikstream commented
> Postman is not a security tool and can already be installed via [AUR](https://aur.archlinux.org/packages/postman-bin). I don't see the interest of adding it in BA.

It is a good tool for Testing APIs, especially if you get Postman Collections from the developers.

2022-02-14 07:53 UTC, noptrix commented
@ikstream thank you

2022-02-14 07:54 UTC, merged