WIP: add starkiller
BlackArch/blackarch pull request #3400
Opened 2022-05-01 17:56 UTC by vittring

### Create starkiller package

Looking for help on this one.

2022-05-08 18:31 UTC, noraj requested changes

2022-05-08 18:31 UTC, noraj commented on packages/starkiller/PKGBUILD
> +pkgname=Starkiller
pkgname should be lowercase, it's not an issue for the URL since github url are case incensitive

2022-05-08 18:31 UTC, noraj commented on packages/starkiller/PKGBUILD
> +_author=BC-SECURITY
remove `_author` and set `BC-SECURITY` in `source`

2022-05-08 18:31 UTC, noraj commented on packages/starkiller/PKGBUILD
> +  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
Use `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'` cf. https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-generic-git

2022-05-08 18:31 UTC, noraj commented on packages/starkiller/PKGBUILD
> +pkgver=1.10.0
`v1.10.0.r0.g16d4e2f`

2022-05-08 18:31 UTC, noraj commented on packages/starkiller/PKGBUILD
> +package() {
cf. our templates

- https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-appimage
- https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-nodejs
- https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-nodejs-npm

2022-07-10 14:16 UTC, noraj requested changes

2022-07-10 14:16 UTC, noraj commented on packages/starkiller/PKGBUILD
> +makedepends=('git' 'yarn' 'npm')
I don't see `yarn` used in the build process?

2022-07-10 14:16 UTC, noraj commented on packages/starkiller/PKGBUILD
> +  # Only install license if required according to
You can remove the comments from the template.

2022-07-10 15:43 UTC, noraj commented
Your package doesn't build at all, please @vittring test your PR with ba-dev https://gist.github.com/noraj/5045be32490f1161161e16fc5820066c or https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Setting_up_a_chroot

2022-07-10 15:47 UTC, noraj requested changes

2022-07-10 15:47 UTC, noraj commented on packages/starkiller/PKGBUILD
> +  npm install --user root -g --prefix "$pkgdir/usr" "$pkgname@"
You used `PKGBUILD-nodejs-npm` template but starkiller is not available on npm so it won't work, please test your packages before submitting them.

```
==> Starting package()...
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/starkiller - Not found
npm ERR! 404 
npm ERR! 404  'starkiller@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2022-07-10T15_44_40_798Z-debug-0.log
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Build failed, check /home/noraj/blackarch_chroot/blackarch/build
Failed to build the package
```

2022-08-15 00:44 UTC, closed without merging

2022-08-15 00:45 UTC, vittring commented
I don't have the time anymore to work on this due to studies and other life occurrences. Anybody else is welcome to take over or start over on this.