Modify git-dumper recipe
BlackArch/blackarch pull request #3405
Opened 2022-05-07 22:36 UTC by ph20

Modify git-dumper recipe for work with last changes

2022-05-08 18:21 UTC, noraj approved these changes
LGTM

```
$ ba-dev -e 'pacman -Ql git-dumper' -p git-dumper-56.32d47a2-2-any.pkg.tar.zst
...
git-dumper /usr/
git-dumper /usr/bin/
git-dumper /usr/bin/git-dumper
git-dumper /usr/lib/
git-dumper /usr/lib/python3.10/
git-dumper /usr/lib/python3.10/site-packages/
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/INSTALLER
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/LICENSE
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/METADATA
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/RECORD
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/REQUESTED
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/WHEEL
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/entry_points.txt
git-dumper /usr/lib/python3.10/site-packages/git_dumper-1.0.6.dist-info/top_level.txt
git-dumper /usr/lib/python3.10/site-packages/git_dumper.py
git-dumper /usr/share/
git-dumper /usr/share/licenses/
git-dumper /usr/share/licenses/git-dumper/
git-dumper /usr/share/licenses/git-dumper/LICENSE
```

2022-05-08 18:24 UTC, noraj requested changes

2022-05-08 18:24 UTC, noraj commented on packages/git-dumper/PKGBUILD
>    echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
`git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`

2022-05-08 18:24 UTC, noraj commented on packages/git-dumper/PKGBUILD
>  pkgver=56.32d47a2
`pkgver=1.0.6.r0.g32d47a2`

2022-05-09 15:52 UTC, ph20 commented on packages/git-dumper/PKGBUILD
>  pkgver=56.32d47a2
Thanks corrected

2022-05-09 15:53 UTC, ph20 commented on packages/git-dumper/PKGBUILD
>    echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
Thanks, corrected

2022-05-14 08:07 UTC, merged