add octopwnweb
BlackArch/blackarch pull request #3454
Opened 2022-06-29 19:41 UTC by marianomarciello

This change add octopwnweb as requested in #3449.

2022-06-29 20:01 UTC, noraj requested changes

2022-06-29 20:22 UTC, marianomarciello commented on packages/octopwnweb/PKGBUILD
> +  cd $pkgname
How can I insert this dependencies ? WSNET can not be build without pip. Should I install WSNET as part of the installation process of octopwnweb ?

2022-06-29 20:39 UTC, noraj commented on packages/octopwnweb/PKGBUILD
> +  cd $pkgname
You should build a package for WSNET from https://github.com/skelsec/wsnet named `python-wsnet` following this template https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-lib-setuptools and then add `python-wsnet` as dependency for octopwnweb, which will make two packages.

2022-06-30 18:53 UTC, marianomarciello reviewed
Hi I have made some change, hope now is better. Sorry for my mistakes but is my first time contributing.

2022-07-01 09:25 UTC, noraj commented
Thx for contributing, I'll test your package soon

2022-07-06 22:30 UTC, noptrix commented
thanks guys. @noraj any updates on progress here?

2022-07-10 14:45 UTC, noraj commented
I'm working on it, it was far from ready.

@marianomarciello You forgot to check https://github.com/skelsec/wsnet/blob/144d5f13c8adfd2f9d793b34352731a852d1ce15/setup.py#L42-L43 in order to add the dependencies.

2022-07-10 14:55 UTC, noraj commented
I also added a wrapper to start the web-server

2022-07-10 14:56 UTC, noraj approved these changes

2022-07-10 14:57 UTC, merged