Update whispers to 2.1.0
BlackArch/blackarch pull request #3481
Opened 2022-07-29 01:49 UTC by adeptex

Hey there, I am the creator of whispers. I saw that awesomely it was included into BlackArch, and I thought I would contribute by updating it to the latest version. [Ownership changed](https://github.com/adeptex/whispers/blob/2.0.6/RELEASE_NOTES.md#dizzy-licensing-changes-dizzy) from Skyscanner to my personal account. In addition, Skyscanner's [version 1](https://github.com/Skyscanner/whispers/) is no longer maintained.

Let me know if you need any additional details. Thanks!

2022-07-29 10:16 UTC, noraj requested changes

2022-07-29 10:16 UTC, noraj commented on packages/whispers/PKGBUILD
> +pkgver=2.1.0.r01
```
$ git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
2.1.0.r0.g8cdc6b1
```

2022-07-29 10:16 UTC, noraj commented on packages/whispers/PKGBUILD
> +license=('GPL-3.0')
change to `GPL3

its has to respect `/usr/share/licenses/common/` names as mentioned here https://wiki.archlinux.org/title/PKGBUILD#license

2022-07-29 10:17 UTC, noraj commented
> Let me know if you need any additional details. Thanks!

Thanks for your contribution, could you apply the requested changes please?

2022-07-29 12:52 UTC, adeptex commented
hey @noraj, done and done! thanks

2022-08-01 08:26 UTC, noraj approved these changes

2022-08-11 02:09 UTC, noptrix commented
@adeptex thanks a lot

2022-08-11 02:09 UTC, merged