ghauri initial pr
BlackArch/blackarch pull request #3548
Opened 2022-10-08 01:02 UTC by dualfade

please review; great new tool under rapid dev.

2022-10-09 00:56 UTC, noraj requested changes

2022-10-09 00:56 UTC, noraj commented on packages/ghauri/PKGBUILD
> +  echo "$(git rev-list --count HEAD)"."$(git rev-parse --short HEAD)"
Use `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'` please, there are tags available.

2022-10-09 01:00 UTC, dualfade commented on packages/ghauri/PKGBUILD
> +  echo "$(git rev-list --count HEAD)"."$(git rev-parse --short HEAD)"
I will adjust. Thanks.

2022-10-11 22:20 UTC, noptrix commented
@dualfade we don't need to use quotes in `cd "$pkgname"`, btw. only when you "strcat()" it, e.g.: `"$pkgname-blah"` or `"$pkgname-$pkgver"`, etc. :) i am gonna remove the quotes here.

2022-10-11 22:21 UTC, merged

2022-10-11 23:36 UTC, dualfade commented
> @dualfade we don't need to use quotes in `cd "$pkgname"`, btw. only when you "strcat()" it, e.g.: `"$pkgname-blah"` or `"$pkgname-$pkgver"`, etc. :) i am gonna remove the quotes here.

I only did so because the latest shellcheck was insisting ;)  got it. Appreciate it.