python-docx2python: added package
BlackArch/blackarch pull request #3665
Opened 2023-01-06 06:38 UTC by D3vil0p3r

Used for LinkScope tool to avoid the usage of Python venv: https://github.com/BlackArch/blackarch/issues/3659

2023-01-07 16:43 UTC, noraj requested changes

2023-01-07 16:43 UTC, noraj commented on packages/python-docx2python/PKGBUILD
> +_pkgname=docx2python
```suggestion
_pkgname=${pkgname#python-}
```

2023-01-07 16:43 UTC, noraj commented on packages/python-docx2python/PKGBUILD
> +url='https://pypi.org/project/docx2python'
```suggestion
url='https://github.com/ShayHill/docx2python'
```

2023-01-07 16:43 UTC, noraj commented on packages/python-docx2python/PKGBUILD
> +sha512sums=('SKIP')
dont skip, skip is only for git

2023-01-08 00:00 UTC, D3vil0p3r commented on packages/python-docx2python/PKGBUILD
> +sha512sums=('SKIP')
Applied SHA512 hash

2023-01-14 14:57 UTC, merged