dracnmap: moving firefox dependency to optdepends
BlackArch/blackarch pull request #3767
Opened 2023-04-06 17:36 UTC by D3vil0p3r

dracnmap code uses firefox for only opening xml but installing one browser only for opening xml is not efficient for users using other browsers.

2023-04-07 15:45 UTC, noraj requested changes

2023-04-07 15:45 UTC, noraj commented on packages/dracnmap/PKGBUILD
> +optdepends=('firefox: XML file opening support')
yes but the script will fail if firefox is not installed so provide a patch as well replacing `firefox` with `xdg-open`. Then add `xdg-utils` to dependencies.

2023-04-11 11:53 UTC, D3vil0p3r commented on packages/dracnmap/PKGBUILD
> +optdepends=('firefox: XML file opening support')
I will giving a further check but I see that the first time this tool has been deployed, it has not been tested at all because it has `apt-get install` that is not an Arch command, and when you run it, it returns a `apt-get command not found` message.

2023-04-11 12:36 UTC, D3vil0p3r commented on packages/dracnmap/PKGBUILD
> +optdepends=('firefox: XML file opening support')
I created `dracnmap-v2.2.sh.patch` as:
```patch
--- a/dracnmap-v2.2.sh	2023-04-11 14:01:33.089329801 +0200
+++ b/dracnmap-v2.2.sh	2023-04-11 14:07:34.933321996 +0200
@@ -113,8 +113,7 @@
    echo [x]::[warning]:this script require Nmap ;
    echo ""
    echo [!]::[please wait]: please install .... ;
-   apt-get update
-   apt-get install nmap
+   pacman -Syu nmap
    echo ""
    sleep 2
    exit
@@ -129,8 +128,7 @@
    echo [x]::[warning]:this script require xterm ;
    echo ""
    echo [!]::[please wait]: please install .... ;
-   apt-get update
-   apt-get install xterm
+   pacman -Syu xterm
    echo ""
    sleep 2
    exit
@@ -183,7 +181,7 @@
                  read ip
                  echo
                  $xterm -A -O -oX Output/$namafile.xml $ip &
-                 firefox Output/$namafile.xml
+                 xdg-open Output/$namafile.xml
            elif test $DrS == '2'
         	then
                   echo
@@ -197,7 +195,7 @@
                   echo
                   $xterm -A -O -oX Output/$namafile.xml $ip &
         	 xsltproc Output/$namafile.xml -o Output/$namafile.html
-        	 firefox Output/$namafile.html
+        	 xdg-open Output/$namafile.html
             elif test $DrS == '3'
         	 then
                   echo
```
then also I created `dracnmap-v2.2-dracOs.sh.patch` as:
```patch
--- a/dracnmap-v2.2-dracOs.sh	2023-04-11 14:01:33.089329801 +0200
+++ b/dracnmap-v2.2-dracOs.sh	2023-04-11 14:07:02.715322691 +0200
@@ -115,8 +115,7 @@
    echo [x]::[warning]:this script require Nmap ;
    echo ""
    echo [!]::[please wait]: please install .... ;
-   apt-get update
-   apt-get install nmap
+   pacman -Syu nmap
    echo ""
    sleep 2
    exit
@@ -131,8 +130,7 @@
    echo [x]::[warning]:this script require xterm ;
    echo ""
    echo [!]::[please wait]: please install .... ;
-   apt-get update
-   apt-get install xterm
+   pacman -Syu xterm
    echo ""
    sleep 2
    exit
@@ -185,7 +183,7 @@
                  read ip
                  echo
                  $urxvt -A -O -oX $HOME/$namafile.xml $ip &
-                 firefox $HOME/$namafile.xml
+                 xdg-open $HOME/$namafile.xml
            elif test $DrS == '2'
         	then
                   echo
@@ -199,7 +197,7 @@
                   echo
                   $urxvt -A -O -oX $HOME/$namafile.xml $ip &
         	 xsltproc $HOME/$namafile.xml -o $HOME/$namafile.html
-        	 firefox $HOME/$namafile.html
+        	 xdg-open $HOME/$namafile.html
             elif test $DrS == '3'
         	 then
                   echo
```
and `PKGBUILD` has the following piece of code:
```
<SNIP>
source=("$pkgname::git+https://github.com/screetsec/Dracnmap.git"
        "dracnmap-v2.2-dracOs.sh.patch"
        "dracnmap-v2.2.sh.patch")
sha512sums=('SKIP'           '2515785b71941da9ac485b0cf99213696f121fdd8b25dc418f7fd2a88cdcc9007dbcaf698d89a76df489b1c85790e0558342ac8fa91912fa1a92295013690406'           '0fb0be0761c16b2b8aa98604f386bd9065a31b1abdad4e02efb5b784d747324e64fbcadcc45b855be2cdc0d30c5083f342399ff28db8e622c49bec943434a0b7')

pkgver() {
  cd $pkgname

  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
}

prepare() {
    cd "$pkgname"

    patch -Np1 -i "$srcdir/dracnmap-v2.2-dracOs.sh.patch"
    patch -Np1 -i "$srcdir/dracnmap-v2.2.sh.patch"
}
<SNIP>
```
but, when I run `makepkg`, I get the following error:
```
==> Making package: dracnmap 69.09d3945-2 (Tue 11 Apr 2023 02:30:41 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating dracnmap git repo...
  -> Found dracnmap-v2.2-dracOs.sh.patch
  -> Found dracnmap-v2.2.sh.patch
==> Validating source files with sha512sums...
    dracnmap ... Skipped
    dracnmap-v2.2-dracOs.sh.patch ... Passed
    dracnmap-v2.2.sh.patch ... Passed
==> Extracting sources...
  -> Creating working copy of dracnmap git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...
patching file dracnmap-v2.2-dracOs.sh
Hunk #4 FAILED at 197.
1 out of 4 hunks FAILED -- saving rejects to file dracnmap-v2.2-dracOs.sh.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
```

2023-04-12 08:31 UTC, noraj commented on packages/dracnmap/PKGBUILD
> +optdepends=('firefox: XML file opening support')
Isn't `dracnmap-v2.2-dracOs.sh` the macOS version?

2023-04-12 11:12 UTC, D3vil0p3r commented on packages/dracnmap/PKGBUILD
> +optdepends=('firefox: XML file opening support')
> Isn't `dracnmap-v2.2-dracOs.sh` the macOS version?

No. It should be related to DracOS Linux, a Debian-based Linux OS: https://github.com/dracos-linux

2023-04-12 13:30 UTC, D3vil0p3r commented on packages/dracnmap/PKGBUILD
> +optdepends=('firefox: XML file opening support')
> Yay but anyway it's a version specific to another distro, so it doesn't make sense to ship it. You need to include `dracnmap-v2.2.sh` only.

It seems legit. By the way, I tried only to patch the `dracnmap-v2.2.sh` but I get the same error:
```bash
<SNIP>
==> Extracting sources...
  -> Creating working copy of dracnmap git repo...
Cloning into 'dracnmap'...
done.
==> Starting prepare()...
patching file dracnmap-v2.2.sh
Hunk #4 FAILED at 195.
1 out of 4 hunks FAILED -- saving rejects to file dracnmap-v2.2.sh.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
```

2023-06-30 08:18 UTC, closed without merging