undbx: add package
BlackArch/blackarch pull request #3814
Opened 2023-04-22 17:26 UTC by D3vil0p3r

Extract e-mail messages from Outlook Express DBX files.

2023-04-22 17:43 UTC, D3vil0p3r commented
Just look that the tags contain the name of the tool.

2023-04-23 11:22 UTC, ikstream commented
This tool has just 31 stars and the last commit was four years ago. I am not sure if we should add this at all.

2023-04-23 11:31 UTC, D3vil0p3r commented
> This tool has just 31 stars and the last commit was four years ago. I am not sure if we should add this at all.

Hey @ikstream thank you for your feedback. I'm retrieveing these tools I created PRs from the new Kali Purple in order to have purple/blue team tools on BlackArch.

2023-04-23 11:37 UTC, ikstream commented
It's a bit suprising to see a tool with just 31 Github Stars to be added to a kali iso.

2023-06-26 17:40 UTC, noraj requested changes

2023-06-26 17:40 UTC, noraj commented on packages/undbx/PKGBUILD
> +  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```suggestion
  git describe --long --tags | sed 's/undbx-//' | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```

2023-06-26 17:40 UTC, noraj commented on packages/undbx/PKGBUILD
> +pkgver=undbx.0.21.r3.g5e31c75
```suggestion
pkgver=0.21.r3.g5e31c75
```

2023-06-26 17:40 UTC, noraj commented on packages/undbx/PKGBUILD
> +makedepends=('autoconf' 'automake' 'git')
```suggestion
makedepends=('git')
```

cf. https://github.com/BlackArch/blackarch/pull/2619

2023-06-26 18:28 UTC, noraj approved these changes
Tested build, install, exec.

2023-06-26 18:29 UTC, merged