hashrat: add package
BlackArch/blackarch pull request #3815
Opened 2023-04-22 17:54 UTC by D3vil0p3r

Hashing tool supporting md5, sha1, sha256, sha512, whirlpool, jh and hmac versions of these. Include recursive file hashing and other features.

2023-04-25 22:27 UTC, noraj commented
It seems similar to rhash, which is in official AL repo, while being less powerful. I don't see the interest of packaging it.

2023-04-26 06:29 UTC, D3vil0p3r commented
> It seems similar to rhash, which is in official AL repo, while being less powerful. I don't see the interest of packaging it.

As you prefer @noraj. I created this PR because I see this tool in the new Kali Purple release and I tried to bring it to BlackArch environment.

2023-06-26 18:56 UTC, noraj requested changes
Outside of those small changes, LGTM. Tested build, install, exec.

2023-06-26 18:56 UTC, noraj commented on packages/hashrat/PKGBUILD
> +makedepends=('autoconf' 'automake' 'git')
```suggestion
makedepends=('git')
```

cf. #2619

2023-06-26 18:56 UTC, noraj commented on packages/hashrat/PKGBUILD
> +groups=('blackarch' 'blackarch-cracker' 'blackarch-crypto')
```suggestion
groups=('blackarch' 'blackarch-crypto' 'blackarch-forensic')
```

2023-06-26 19:02 UTC, noraj approved these changes

2023-06-26 19:02 UTC, merged