initial commit; iamspy
BlackArch/blackarch pull request #3840
Opened 2023-05-13 01:16 UTC by dualfade

please review; thank you

2023-05-13 20:43 UTC, noraj requested changes

2023-05-13 20:43 UTC, noraj commented on packages/iamspy/PKGBUILD
> +pkgname=IAMspy
```suggestion
pkgname=iamspy
```

always lowercase

2023-05-13 20:43 UTC, noraj commented on packages/iamspy/PKGBUILD
> +pkgdesc='a library that utilises the Z3 prover to attempt to answer questions about AWS IAM.'
```suggestion
pkgdesc='A library that utilises the Z3 prover to attempt to answer questions about AWS IAM.'
```

2023-05-13 21:02 UTC, dualfade commented
Adjusted

2023-05-14 12:46 UTC, noraj approved these changes
LGTM

2023-05-17 12:53 UTC, dualfade commented
Please hold. 

Developer would like to distribute from pypi for release versioning.

Thank you.

2023-10-18 15:45 UTC, dualfade commented
Let me check in with the dev. I will update this. Thanks !

2023-12-04 16:25 UTC, dualfade commented
Not fixed yet; removing pr for now. Thanks all.

2023-12-04 16:25 UTC, closed without merging