add GooFuzz
BlackArch/blackarch pull request #3855
Opened 2023-06-12 21:13 UTC by marianomarciello

Add GooFuzz as requested in #3811

2023-06-13 07:19 UTC, noraj approved these changes

2023-06-15 19:30 UTC, noptrix requested changes
@marianomarciello Thank you for this. But a couple of things: I don't see any entries in `depends=()` but you use at least `curl`. We need to make sure that we add any external tools as dependencies inside `depends=()` you use in this shell script. Second thing: Please remove the name of the tool inside `pkgdesc`. You can say "A script written in Bash..." or sth similar.

2023-06-15 20:17 UTC, marianomarciello commented
Hi @noptrix thank your for your revision and for your time.

2023-06-17 07:50 UTC, noptrix approved these changes

2023-06-17 07:50 UTC, merged

2023-12-10 18:09 UTC, m3n0sd0n4ld commented
Thank you for add GooFuzz tool!