Add RhinoSecurityLabs AWS IAM Privilege Escalation tool
BlackArch/blackarch pull request #3896
Opened 2023-07-03 22:51 UTC by cyberqueenmeg

Hi,

I've revamped the RhinoSecLabs AWS IAM privesc tool (it was old), and would love to add it to blackarch. Thanks!

2023-07-04 09:10 UTC, noraj requested changes

2023-07-04 09:10 UTC, noraj commented on packages/aws_iam_privesc/PKGBUILD
> +url='https://github.com/cyberqueen-meg/log4j-bypass'
```suggestion
url='https://github.com/cyberqueenmeg/aws_iam_privesc'
```

2023-07-04 09:10 UTC, noraj commented on packages/aws_iam_privesc/PKGBUILD
> +source=("git+https://github.com/cyberqueen-meg/$pkgname.git")
```suggestion
source=("git+https://github.com/cyberqueenmeg/$pkgname.git")
```

2023-07-04 09:10 UTC, noraj commented on packages/aws_iam_privesc/PKGBUILD
> +pkgname=aws_iam_privesc
Maybe

```suggestion
pkgname=aws-iam-privesc
_pkgname=aws_iam_privesc
```

and replace `$pkgname` with `$_pkgname`

2023-07-04 09:10 UTC, noraj commented on packages/aws_iam_privesc/PKGBUILD
> +cd /usr/share/$pkgname
If the following works it's better not to `cd`

```
exec python3 /usr/share/$pkgname/aws_escalate.py "\$@"
```

2023-07-04 17:01 UTC, cyberqueenmeg commented on packages/aws_iam_privesc/PKGBUILD
> +cd /usr/share/$pkgname
updated the code

2023-07-04 17:02 UTC, cyberqueenmeg commented
@noraj - thanks for the feedback, I made all requested changes.

2023-07-04 19:36 UTC, noraj approved these changes
LGTM

2023-07-06 18:04 UTC, merged

2023-07-06 18:14 UTC, noptrix commented
@cyberqueenmeg thanks for this. please check my changes for future usage of PKGBUILD of such a package.