shellcodecs: broken
BlackArch/blackarch pull request #4323
Opened 2024-11-01 00:52 UTC by D3vil0p3r

https://github.com/BlackArch/blackarch/issues/2494

2024-11-01 18:32 UTC, noraj requested changes

2024-11-01 18:32 UTC, noraj commented on lists/broken
> +shellcodecs # discontinued, source unavailable
```suggestion
shellcodecs # discontinued, source unavailable, #2494
```

2024-11-01 22:47 UTC, merged

2026-02-22 16:18 UTC, abuobuotalebt-svg commented
D3vil0p3r:patch-14

2026-02-22 16:27 UTC, abuobuotalebt-svg commented
D3vil0p3r:patch-14