dissect: add module packages
BlackArch/blackarch pull request #4361
Opened 2024-11-18 15:05 UTC by D3vil0p3r

Close https://github.com/BlackArch/blackarch/issues/3688

2024-11-19 19:40 UTC, noraj requested changes
That's a lot of work. I don't have time to test this right now. At a glance I can see license identifiers are old, could you upgrade to SPDX identifier please?

I hope in the long run that won't turn to be a hell to maintain and that we won't need to switch to virtualenv.

2024-11-19 19:50 UTC, D3vil0p3r commented
Licenses upgraded. I did basic tests on all of them during packaging and they worked correctly.

2024-11-19 19:53 UTC, noraj commented
> Licenses upgraded. I did basic tests on all of them during packaging and they worked correctly.

Yes but it will be soon obsolete when [AL RFC-0016](https://rfc.archlinux.page/0016-spdx-license-identifiers/) will be finalised.

https://wiki.archlinux.org/title/PKGBUILD#license

> Note: Arch Linux is [currently undergoing](https://rfc.archlinux.page/0016-spdx-license-identifiers/) a transition to SPDX style identifiers. Some issues may still require ironing out. This section focuses on the SPDX format. If you encounter any trouble, please report them and discuss with the community.

2024-11-19 19:56 UTC, D3vil0p3r commented
At least we can manage that massive license change by 1 or 2 sed commands. Btw thanks for the last link.

2024-11-24 11:35 UTC, D3vil0p3r commented on packages/python-acquire/PKGBUILD
> +depends=('python' 'python-dissect.cstruct' 'python-dissect.target' 'python-minio' 'python-pycryptodome' 'python-requests' 'python-requests-toolbelt' 'python-rich')
Fixed, thanks

2024-11-24 11:35 UTC, D3vil0p3r commented on packages/python-acquire/PKGBUILD
> +check() {
Fixed

2024-11-24 14:47 UTC, merged

2024-11-24 16:11 UTC, noptrix commented
@D3vil0p3r wrong arch setups :/ i've fixed them - please check my last commits for `dissect`. again, as soon as something gets compiled to a binary, we need to use `('x86_64', 'aarch64')`, otherwise leave as `('any')`

2024-11-24 16:24 UTC, D3vil0p3r commented
Sorry @noptrix during the building of them I noted that it produced `bdist-x86_64` strings.. so I assumed all of them needed `('x86_64', 'aarch64')`. How did you check that, instead, `any` was needed for those dissect in the last commits?

2024-11-24 16:31 UTC, noptrix commented
@D3vil0p3r no worries at all, just for the future... uhm, i am building them and see that nothign gets compiled, no binaries built. maybe there is another way to do that easier...