+ sstimap initial commit
BlackArch/blackarch pull request #4365
Opened 2024-11-18 20:16 UTC by dualfade

please review.
Thanks.

2024-11-18 20:21 UTC, D3vil0p3r commented on packages/sstimap/PKGBUILD
> +}
```suggestion
pkgver() {
  cd $_pkgbase

  ( set -o pipefail
    git describe --long --tags --abbrev=7 2>/dev/null |
      sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
    printf "%s.%s" "$(git rev-list --count HEAD)" \
      "$(git rev-parse --short=7 HEAD)"
  )
}
```

2024-11-18 20:22 UTC, D3vil0p3r commented on packages/sstimap/PKGBUILD
> +license=('gpl3')
```suggestion
license=('GPL-3.0')
```

2024-11-18 20:22 UTC, D3vil0p3r commented on packages/sstimap/PKGBUILD
> +groups=('blackarch' 'blackarch-webapp' 'blackarch-exploitation')
```suggestion
groups=('blackarch' 'blackarch-exploitation' 'blackarch-webapp')
```

2024-11-18 20:23 UTC, D3vil0p3r commented on packages/sstimap/PKGBUILD
> +url='URL pointing to download section of package'
```suggestion
url='https://github.com/vladko312/SSTImap'
```

2024-11-18 20:27 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +url='URL pointing to download section of package'
my bad. fixed.

2024-11-18 20:27 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +groups=('blackarch' 'blackarch-webapp' 'blackarch-exploitation')
re ordered.

2024-11-18 20:27 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +license=('gpl3')
forgot to fix this. fixed.

2024-11-18 20:29 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +}
Is this something new we are doing it now ?  This is not in the pkgbuild scripts. let me know. Thanks.

2024-11-18 20:32 UTC, D3vil0p3r commented on packages/sstimap/PKGBUILD
> +}
[Here](https://github.com/BlackArch/blackarch-pkgbuilds/blob/b8fd779ec987a8d29f543a5cc5b729074ece638a/PKGBUILD-generic-git#L17) the reference. I think it should be extended to all PKGBUILD templates dealing with git: https://github.com/BlackArch/blackarch-pkgbuilds/pull/24

2024-11-19 19:25 UTC, noraj requested changes

2024-11-19 19:30 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +makedepends=('git' 'python-setuptools' 'python-pip')
Will remove.

2024-11-19 19:35 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +license=('GPL-3.0')
Will update

2024-11-19 19:41 UTC, D3vil0p3r requested changes

2024-11-19 19:41 UTC, D3vil0p3r commented on packages/sstimap/PKGBUILD
> +license=('PL-3.0-or-later')
```suggestion
license=('GPL-3.0-or-later')
```

2024-11-19 19:49 UTC, dualfade commented on packages/sstimap/PKGBUILD
> +license=('PL-3.0-or-later')
Muther of christ. Fixing.....

2024-11-19 20:46 UTC, merged

2024-11-19 20:59 UTC, dualfade commented
Thanks all.